@baseUrl = http://localhost:5144
@validDriver = "76ccefd1-30e9-402c-a61a-18314569c789"
@validVehicle = "119e6e44-fe0e-465e-918f-2a50ed92bed3"

###
POST {{baseUrl}}/assignments
Content-Type: application/json
Accept: application/json

{
  "driverId": {{validDriver}},
  "vehicleId": {{validVehicle}},
  "startUtc": "2026-03-05T10:00:00Z",
  "endUtc": "2026-03-05T12:00:00Z"
}

###

POST {{baseUrl}}/assignments
Content-Type: application/json
Accept: application/json

{
  "driverId": {{validDriver}},
  "vehicleId": {{validVehicle}},
  "startUtc": "2026-03-05T11:00:00Z",
  "endUtc": "2026-03-05T13:00:00Z"
}

###

POST {{baseUrl}}/assignments
Content-Type: application/json
Accept: application/json

{
  "driverId": {{validDriver}},
  "vehicleId": {{validVehicle}},
  "startUtc": "2026-03-04T15:00:00Z",
  "endUtc": "2026-03-05T14:00:00Z"
}

###

