@baseUrl = http://localhost:5144/vehicles

### Empty registrationnumber
POST {{baseUrl}}
Content-Type: application/json
Accept: application/json

{
    "registrationnumber": ""
}

### To long registrationnumber
POST {{baseUrl}}
Content-Type: application/json
Accept: application/json

{
    "registrationnumber": "lasdkjfaölsdjföalksdjfalöksdk3sdlfalaksjdflkcvhueoi"
}