@baseUrl = http://localhost:5144/vehicles

### 

GET {{baseUrl}}?registrationnumber=lasdkjfaölsdjföalksdjfalöksdk3sdlfalaksjdflkcvhueoi
Accept: application/json

### 

GET {{baseUrl}}?limit=-1
Accept: application/json

### 

GET {{baseUrl}}?limit=1000
Accept: application/json

### 

GET {{baseUrl}}?offset=-1
Accept: application/json
